name: postapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  floating_action_bubble: 1.0.9
  url_launcher: ^5.4.5
  http:
  provider:
  mobx: ^1.0.2+2
  flutter_mobx: ^1.0.1
  mobx_codegen: ^1.0.2
  path_provider:
  

dev_dependencies:
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter
  

flutter:

  uses-material-design: true

  assets:
  - lib/images/

  fonts:
    - family: RobotoSlab
      fonts:
        - asset: lib/fonts/RobotoSlab-SemiBold.ttf

    - family: RobotoSlab-Regular
      fonts:
        - asset: lib/fonts/RobotoSlab-Regular.ttf

